### ISSUE TITLE
rvierdiiev - FundingRateArbitrage allows users to avoid loss

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#12]
rvierdiiev

high

# FundingRateArbitrage allows users to avoid loss

## Summary
FundingRateArbitrage allows users to avoid loss as they can just simply not withdraw and keep jusd.
## Vulnerability Detail
Users [provide usdc into FundingRateArbitrage contract](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L266). Then contract [deposits same amount of jusd](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L267) to user's account and user can withdraw those funds and use them.

USDC that were provided by users are going to be swapped to eth, then used to borrow jusd in the bank and then use jusd to participate in perp trading. The aim of FundingRateArbitrage is to earn additional funds from pepr markets and increase index price, which means that user's will be able to get more funds then they have deposited.

As FundingRateArbitrage will hold some positions in perp market, then it's possible that they will loose some funds(because of price change) and they can even be liquidated, which makes it possible to index price become less than 1. Such case signals that FundingRateArbitrage contract faced a loss and not users who will `requestWithdraw` will receive smaller amount of usdc.

However in this finding i want to flag, that in case if such thing will happen, then user will not call `requestWithdraw` anymore, because it means that they will need to burn bigger amount of jusd for smaller amount of usdc. All user will likely hold jusd or swap it on some market and get better price.

This will mean pure loss of jusd for the protocol as those jusd was covered by usdc.
So currently user can be sure that they will not lose funds with FundingRateArbitrage contract.
## Impact
Loss is not distributed among depositors.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
I would redesign this contract to be similar to erc4626 vault that mints own tokens and do not deposit jusd for users.

Duplicate of #35

**Comment by rvierdiyev** [comment]
Escalate
This is not duplicate of #35 and is talking about such design in FundingRateArbitrage that allows depositors to avoid any loss.
Also this was confirmed as issue by sponsor with decision that `users need to take the risk of loss`.

**Comment by nevillehuang** [comment]
@JoscelynFarr can you take a look? Imo, I see no difference in the invalidation reason stated in #35 and this. Both states similar reasonings to why index prices can fall.

**Comment by rvierdiiev** [comment]
I am not talking about loss of funds for user here. I am talking about loss of funds for protocol and about wrong implementation that doesn't distribute losses on users.

**Comment by JoscelynFarr** [comment]
> @JoscelynFarr can you take a look? Imo, I see no difference in the invalidation reason stated in #35 and this. Both states similar reasonings to why index prices can fall.

Agree with you, I think there are same.

**Comment by nevillehuang** [comment]
@rvierdiyev I don't see the funds lost here that impacts the protocol from users retaining JUSD. I believe that is the best case scenario for them when the admins of the trusted protocol makes a bad trade, given they retain their original JUSD value relative to the collateral deposited. So I believe your issue is a duplicate of #35 albeit I'm not sure your recommendation applies, given if it was ERC4626 like, if protocol makes a bad trade, the exchange rate for shares would be influenced anyways.

**Comment by rvierdiiev** [comment]
@nevillehuang 
Jusd should be backed 1:1 with USDC. When users deposit their usdc into the FundingRateArbitrage contract, then protocol mints same amount of jusd for them. But in case if FundingRateArbitrage make a loss, then it means that judc that was minted for the depositors is not backed anymore by protocol. This is what i meant when talking about loss for protocol.

**Comment by Evert0x** [comment]
I believe this issue identifies the same root cause as 35, planning to reject escalation and keep issue state as is.

**Comment by Czar102** [comment]
Result:
Invalid
Duplicate of #35

The severity may still be altered due to an escalation on #35.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/12/#issuecomment-1913086534): rejected
