### ISSUE TITLE
rudolph - Potential risk of private key leakage

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#13]
rudolph

medium

# Potential risk of private key leakage

## Summary
The withdrawal of assets requires a 24-hour approval time, users must first deposit `jusd` assets into the `FundingRateArbitrage` contract, while the privileged wallet address can withdraw `jusd` assets from the current contract via the [`refineJUSD()`](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L151) method, so if the private key of this privileged address is compromised, it may damage the assets of the user waiting for the withdrawal audit.

## Vulnerability Detail
Users wishing to withdraw funds must first deposit JUSD tokens using the method below.
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L277C3-L277C3
```solidity=277
    /// @notice this function is to submit a withdrawal which wiil permit by our system in 24 hours
    /// The main purpose of this function is to capture the interest and avoid the DOS attacks.
    /// @dev users need to withdraw jusd from trading system firstly or by jusd, then transfer jusd to
    /// the pool and get usdc back
    /// @param repayJUSDAmount is the repat jusd amount
    function requestWithdraw(uint256 repayJUSDAmount) external returns (uint256 withdrawEarnUSDCAmount) {
        IERC20(jusd).safeTransferFrom(msg.sender, address(this), repayJUSDAmount);
        ...
```

Before the user withdraws, the leak of the privileged private key will cause losses to the user and the contract.
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L151
```solidity=151
    function refundJUSD(uint256 amount) public onlyOwner {
        IERC20(jusd).safeTransfer(msg.sender, amount);
    }
```

## Tool used
Foundry

Manual Review

## Recommendation
Protect the private key well or use a multi-signature wallet to avoid the risk of a single private key being compromised.

**Comment by nevillehuang** [comment]
Invalid, private keys are users responsibility, not a smart contract risk.
