### ISSUE TITLE
rvierdiiev - withdrawSettleFee increase can make some withdrawals to be stuck

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#14]
rvierdiiev

medium

# withdrawSettleFee increase can make some withdrawals to be stuck

## Summary
In case `withdrawSettleFee` will increase then it can make some withdrawals to be stuck, because of the check in the `permitWithdrawRequests` function.
## Vulnerability Detail
When user flags withdraw, then there is a check, that amount to be withdrawn [is bigger than `withdrawSettleFee`](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L294). Same check exists, [when owner executes withdraw](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L310).

In case if `withdrawSettleFee` [will be increased](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L148) to the value that is bigger than already pending withdraw, then owner will not be able to settle such withdraw and those amount of funds that belongs to withdrawer and is now less than `withdrawSettleFee` will stuck.
## Impact
Some deposits may stuck after `withdrawSettleFee` increase.
## Code Snippet
Provided above
## Tool used

Manual Review

## Recommendation
Provide ability for user to cancel withdraw in some cases.

**Comment by nevillehuang** [comment]
Invalid, `withdrawSettleFee()` can only be adjusted by owner, so this would constitue admin breaking assumptions not valid based on sherlock [rules, see point 5.1 and 5.3](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)
