### ISSUE TITLE
T1MOH - ConstOracle.sol doesn't fully implement IPriceSource.sol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#2]
T1MOH

medium

# ConstOracle.sol doesn't fully implement IPriceSource.sol

## Summary
ConstOracle.sol doesn't have method `getAssetPrice()`

## Vulnerability Detail
It is specified in README that ConstOracle will be set after collateral is delisted:
>unused contract: in the delist, we will replace the oracle to make the price anchored a fixed price

However ConstOracle.sol doesn't have method `getAssetPrice()`, this will cause a revert in some other interactions:
1) Liquidator can't receive that delisted asset in liquidation., note that he can specify any collateral that user deposited.
```solidity
function liquidate(...)
        external
        override
        isValidOperator(msg.sender, liquidator)
        nonFlashLoanReentrant
        returns (Types.LiquidateData memory liquidateData)
    {
        ...
        liquidateData = _calculateLiquidateAmount(liquidated, collateral, amount);
        ...
    }

    function _calculateLiquidateAmount(
        address liquidated,
        address collateral,
        uint256 amount
    )
        internal
        view
        returns (Types.LiquidateData memory liquidateData)
    {
        Types.UserInfo storage liquidatedInfo = userInfo[liquidated];
        require(_isStartLiquidation(liquidatedInfo, tRate), Errors.ACCOUNT_IS_SAFE);
        Types.ReserveInfo memory reserve = reserveInfo[collateral];
@>      uint256 price = IPriceSource(reserve.oracle).getAssetPrice();
        ...
    }
```
2) Some view functions will revert, but that's low impact
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/ed4a8483da11bcc04ced10de899038bcead087b3/smart-contract-EVM/src/JUSDView.sol#L30
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/ed4a8483da11bcc04ced10de899038bcead087b3/smart-contract-EVM/src/JUSDView.sol#L55

## Impact
Liquidator can't liquidate delisted collateral

## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/ed4a8483da11bcc04ced10de899038bcead087b3/smart-contract-EVM/src/oracle/ConstOracle.sol#L8

## Tool used

Manual Review

## Recommendation
Add missing method

**Comment by nevillehuang** [comment]
Invalid, intended that constant oracle does not supported asset price
