### ISSUE TITLE
AuditorPraise - approveTarget may not == swapTarget

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#20]
AuditorPraise

medium

# approveTarget may not == swapTarget

## Summary
approveTarget may not == swapTarget for some DEXES, this may cause issues with approval as the DepositStableCoinToDealer.sol contract only approves approveTarget for swaps. 

In a situation where approveTarget != swapTarget, swapTarget isnt approved to do swaps in DepositStableCoinToDealer.depositStableCoin()

## Vulnerability Detail
see summary.

An example of such dexes that approveTarget may not == swapTarget is DODO. There could still be some other ones too.

## Impact
In a situation where approveTarget != swapTarget, swapTarget isn't approved to do swaps in DepositStableCoinToDealer.depositStableCoin()

The DepositStableCoinToDealer.depositStableCoin() function may revert due to lack of approval.
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/DepositStableCoinToDealer.sol#L52-L54
## Tool used

Manual Review

## Recommendation
check with an if statement whether  approveTarget != swapTarget, then approve swapTarget too.

**Comment by nevillehuang** [comment]
Invalid, user input error not valid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid

> 4. User input validation: User input validation to prevent user mistakes is not considered a valid issue
