### ISSUE TITLE
cawfree - Signature Replay: `JOJOStorage` caches the `DOMAIN_SEPARATOR` in the constructor.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#23]
cawfree

medium

# Signature Replay: `JOJOStorage` caches the `DOMAIN_SEPARATOR` in the constructor.

## Summary

A cached [`domainSeparator`](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JOJOStorage.sol#L20C16-L20C16) can lead to replay attacks on a hard-forked chain.

## Vulnerability Detail

As a gas optimization, the [`domainSeparator`](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JOJOStorage.sol#L20C16-L20C16) is cached in the constructor of [`JOJOStorage`](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JOJOStorage.sol#L20C16-L20C16) under the expectation that the `block.chainId` cannot change.

However, in the instance of a chain fork, the result would be two independent protocol instances which share common signature namespace digests, causing a single signature to satisfy domain separation checks on two separate domains.

## Impact

This issue is [commonly assessed](https://github.com/sherlock-audit/2023-12-dodo-gsp-judging/issues/113) as medium in severity.

The upcoming ArbOS upgrade indicates that the Arbitrum Foundation intend to adopt the design philosophy of hard forks, which historically result in the creation of two parallel chains, instead of the chain-death of the original rules chain.

## Code Snippet

```solidity
constructor() Ownable() {
    domainSeparator = EIP712._buildDomainSeparator("JOJO", "1", address(this));
}
```

## Tool used

Manual Review

## Recommendation

The `domainSeparator` should be computed dynamically where needed.

**Comment by nevillehuang** [comment]
Invalid based on [recent judgements](https://github.com/sherlock-audit/2023-12-dodo-gsp-judging/issues/113#issuecomment-1903799357)
