### ISSUE TITLE
joicygiore - The `FundingRateArbitrage` contract function has not yet been developed,Users are not able to earn interest as expected

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#25]
joicygiore

medium

# The `FundingRateArbitrage` contract function has not yet been developed,Users are not able to earn interest as expected

## Summary
The functions related to [Convenience: Users only need to deposit funds into the JOJO platform to enjoy the automated funding rate arbitrage service without the need for complex calculations and operations.](https://about.jojo.exchange/jojo-1/trade/jojos-funding-rate-arbitration) in the `FundingRateArbitrage` contract have not yet been developed
## Vulnerability Detail
```js
    mapping(address => uint256) public earnUSDCBalance;
    mapping(address => uint256) public jusdOutside;
    mapping(address => uint256) public maxUsdcQuota;
```
The above variables in the contract are used to save the user's fund status, but by checking all funcitons in the contract and testing, it is found that the [Convenience: Users only need to deposit funds into the JOJO platform to enjoy the automated funding rate arbitrage service without the need for complex calculations and operations.](https://about.jojo.exchange/jojo-1/trade/jojos-funding-rate-arbitration),[LPs can deposit USDC into the arbitrage pool via the deposit function, earning interest. ](https://github.com/JOJOexchange/smart-contract-EVM)  introduced in the official documentation is not implemented in the source code of the contract.
## Impact
The contract functionality is not yet complete
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L254-L300
## Tool used
Manual Review
## Recommendation
Improve the relevant features described in the documentation

**Comment by nevillehuang** [comment]
Invalid, future integrations are not valid based on sherlock rules and hence are out of scope
