### ISSUE TITLE
AuditorPraise - `collateral` should approve `jusdBank` to 0 first because collateral can be USDT

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#29]
AuditorPraise

medium

# `collateral` should approve `jusdBank` to 0 first because collateral can be USDT

## Summary
USDT needs approvals to be set to 0 first
## Vulnerability Detail
`collateral` can be USDT and the collateral doesn't approve `jusdBank` to 0 first before setting it to uint256.max
## Impact
since collateral doesn't set `jusdBank` to 0 first USDT is incompatible as a collateral.
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateArbitrage.sol#L77
## Tool used

Manual Review

## Recommendation
make `collateral` approve `jusdBank` to 0 first because collateral can be USDT

**Comment by nevillehuang** [comment]
Invalid, max approval is only execute once upon deployment in the constructor, so this is not required
