### ISSUE TITLE
bughuntoor - Project may be unable to be deployed on Arbitrum due to incompatibility with Shanghai hardfork

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#32]
bughuntoor

medium

# Project may be unable to be deployed on Arbitrum due to incompatibility with Shanghai hardfork

## Summary
Project might be unusable upon deployment due to not supporting PUSH0 OPCODE 

## Vulnerability Detail
The project uses unsafe pragma (^0.8.20) which by default uses PUSH0 OPCODE. However, Arbitrum currently does not [support](https://docs.arbitrum.io/for-devs/concepts/differences-between-arbitrum-ethereum/solidity-support#differences-from-solidity-on-ethereum) it. 

This means that the produced bytecode for the different contracts won't be compatible with Arbitrum as it does not yet support the Shanghai hard fork.

## Impact
Unusable contracts, will need redeploy

## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JOJOExternal.sol#L6

## Tool used

Manual Review

## Recommendation
change pragma to 0.8.19 or change the EVM version

**Comment by 0xMR0** [comment]
Escalate

This should be informational or low severity at best. This issue doesn't justifies medium severity at sherlock unless the inscope contracts are affected by this issue. The issue does not mention any such information affecting in scope contracts.

[This](https://github.com/sherlock-audit/2023-12-symm-io-judging/issues/4) was similar issue submitted during Symmio audit and it was invalidated by sherlock.

Feel free to correct if i am missing something.

**Comment by sherlock-admin** [comment]
> Escalate
> 
> This should be informational or low severity at best. This issue doesn't justifies medium severity at sherlock unless the inscope contracts are affected by this issue. The issue does not mention any such information affecting in scope contracts.
> 
> [This](https://github.com/sherlock-audit/2023-12-symm-io-judging/issues/4) was similar issue submitted during Symmio audit and it was invalidated by sherlock.
> 
> Feel free to correct if i am missing something.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@0xMR0 

- The difference between this and the issue you pointed out is that there is evidence via `foundry.toml` that if deployed wrongly, the whole contract will be DoSed, whereas the issue in symmio uses hardhat, which defaults to paris evm version

- I am borderline on this one too, given the fix can be both in-scope contract and out-of-scope configuration, but I believe the evidence from the github repo suffice to show that it is a valid medium severity issue given an explicit fix is required, with the root cause being a combination of both inscope contracts and out of scope configuration file

**Comment by ghost** [comment]
Correct me if I am wrong.
Based on my thorough analysis of the [rules of Sherlock](https://docs.sherlock.xyz/audits/judging/judging), I am confident in asserting that there is no risk of fund loss in this scenario. My understanding is that the issue primarily involves adapting the EVM version in the codebase for deployment on an alternative mainnet, such as Arbitrum. This adjustment appears to be, at most, a matter of low severity, primarily serving an informational purpose. It's crucial to recognize that this change does not compromise the security or integrity of the funds, aligning perfectly with the established protocols of Sherlock(no loss of funds).

**Comment by nevillehuang** [comment]
@Hash01011122 As long as it impacts core contract functionality, there is no requirement that there needs to be a definite loss of funds, however, I can agree that it is borderline out of scope, but not completely.

https://discord.com/channels/812037309376495636/881726370370158592/1200387163624308797

**Comment by 0xMR0** [comment]
How this issue is breaking core contract functionality? 

Compiler config is out of scope and the compiler version to be deployed with is decided by protocol team i.e admin. Admin is trusted per readme. Arbitrum does not support PUSH0 is well known issue since May,2023 and since the admin is trusted, it is expected that the admin/developer won't deploy the contract with incompatible compiler with on-chain.

Refer [this](https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/84#issuecomment-1784867692) judgement for similar issue given by sherlock judging head.

**Comment by nevillehuang** [comment]
@0xMR0 Thanks for the response, this issue should be invalid

**Comment by detectiveking123** [comment]
This is invalid.

**Comment by JoscelynFarr** [comment]
Fixed PR: https://github.com/JOJOexchange/smart-contract-EVM/commit/7104f583a7452ca238eb30fc45ce2a030f72d103

**Comment by IAm0x52** [comment]
Fix looks good. Changes solidity version from 8.20 to 8.19.

**Comment by Evert0x** [comment]
Planning to accept escalation based on similar reasoning as this previous judgment https://github.com/sherlock-audit/2023-10-real-wagmi-judging/issues/84#issuecomment-1784867692

**Comment by T1MOH593** [comment]
@Evert0x Isn't escalation should be accepted with referred reasoning?

**Comment by 0xMR0** [comment]
@Evert0x I said low severity in escalation which is by default invalid at sherlock then i think the escalation should be accepted.

**Comment by Evert0x** [comment]
@T1MOH593 @0xMR0 correct, edited original message.

**Comment by Czar102** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xMR0](https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/32/#issuecomment-1913097111): accepted
