### ISSUE TITLE
bughuntoor - User can force revert max deposits to JUSDBank

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#33]
bughuntoor

medium

# User can force revert max deposits to JUSDBank

## Summary
User can force revert max deposits to `JUSDBank`

## Vulnerability Detail
Within the `JUSDBank` contract, users can deposit collateral and borrow `JUSD` against it. The problem is there is `maxDepositAmountPerAccount`. This would mean that if a user attempts to stake up to max balance, an adversary can just grief deposit 1 wei and force the user's tx to revert. 

```solidity
        require(
            user.depositBalance[collateral] <= reserve.maxDepositAmountPerAccount,
            Errors.EXCEED_THE_MAX_DEPOSIT_AMOUNT_PER_ACCOUNT
        );
``` 

This creates a serious risk in certain scenario when user is close to liquidation. 
 1. User is close to liquidation. 
 2. User attempts to deposit up to the allowed cap. 
 3. Another user sees this and front-runs it, depositing 1 wei.
 4. The innocent user's tx reverts
 5. Due to the user being unable to deposit, they might get unfairly liquidated.

## Impact
Unfair liquidation, griefing.

## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JUSDBank.sol#L252C1-L264C6

## Tool used

Manual Review

## Recommendation
Either set up a minimum deposit amount or if the user tries to deposit more than the cap, deposit up to the cap and refund the rest.

**Comment by nevillehuang** [comment]
Invalid, the user can simply execute partial deposits, so this is a non-issue. Additionally, front-running is not a issue on arbitrum given mempool is private.
