### ISSUE TITLE
bareli - The return value of an external call is not stored in a local or state variable.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#41]
bareli

medium

# The return value of an external call is not stored in a local or state variable.

## Summary
approve(address spender, uint256 amount) → bool

## Vulnerability Detail
   IERC20(usdc).approve(jojoDealer, usdcAmount);
## Impact
we will not know whether its approved or not.
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/DepositStableCoinToDealer.sol#L66

## Tool used

Manual Review

## Recommendation
Ensure that all the return values of the function calls are used.

**Comment by nevillehuang** [comment]
Invalid, USDC on arbitrum will only revert when approval fails, so boolean value will always returns true if successful, and so is not required to be explicitly stored and checked
