### ISSUE TITLE
bareli - Input Validation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#44]
bareli

medium

# Input Validation

## Summary
Input Validation: The function updateFundingRate assumes that the lengths of perpList and rateList are equal and does not perform any checks to ensure this. Malicious input could cause the function to revert or behave unexpectedly.

## Vulnerability Detail
function updateFundingRate(address[] calldata perpList, int256[] calldata rateList) external onlyOwner {
        for (uint256 i = 0; i < perpList.length;) {
            address perp = perpList[i];
            int256 oldRate = IPerpetual(perp).getFundingRate();
            uint256 maxChange = getMaxChange(perp);
          @>  require((rateList[i] - oldRate).abs() <= maxChange, "FUNDING_RATE_CHANGE_TOO_MUCH");
            fundingRateUpdateTimestamp[perp] = block.timestamp;
            unchecked {
                ++i;
            }
        }
        IDealer(dealer).updateFundingRate(perpList, rateList);
    }
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FundingRateUpdateLimiter.sol#L37
## Tool used

Manual Review

## Recommendation
use a require statement for the array length verification.

**Comment by nevillehuang** [comment]
Invalid based on sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

> 4. User input validation: User input validation to prevent user mistakes is not considered a valid issue.
