### ISSUE TITLE
bareli - Missing JOJOStorage Import:

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#47]
bareli

medium

# Missing JOJOStorage Import:

## Summary
Missing JOJOStorage Import: The comment mentions a JOJOStorage contract for data structure, but it's not explicitly imported. If JOJOStorage is a contract that should be inherited, it needs to be imported and listed in the contract inheritance list.

## Vulnerability Detail
/// data structure -> JOJOStorage
contract JOJODealer is JOJOExternal, JOJOOperation, JOJOView {
    constructor(address _primaryAsset) JOJOStorage() {
        state.primaryAsset = _primaryAsset;
    }

## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JOJODealer.sol#L16
## Tool used

Manual Review

## Recommendation
import JOJOStorage  
import "./JOJOStorage.sol";

**Comment by nevillehuang** [comment]
Invalid, JOJOStorage is inherited by JOJOOperation [here](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JOJOOperation.sol#L16)
