### ISSUE TITLE
bareli - no check for same decimal for primary and secondary.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#48]
bareli

medium

# no check for same decimal for primary and secondary.

## Summary
it has been mention that secondary assert must have same decimal as primary asset.
## Vulnerability Detail
 /// @notice Secondary asset can only be set once.
    /// Secondary asset must have the same decimal with primary asset.
    function setSecondaryAsset(address _secondaryAsset) external onlyOwner {
        Operation.setSecondaryAsset(state, _secondaryAsset);
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JOJOOperation.sol#L69
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, this would consitute admin input error not valid based on sherlock [rules, see point 5.](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid). Additionally, see comments in #84
