### ISSUE TITLE
Homebrew - Potential  block timestamp manipulation vulnerability

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#5]
Homebrew

medium

# Potential  block timestamp manipulation vulnerability

## Summary
Block Timestamp Manipulation

## Vulnerability Detail
The contract uses block.timestamp to validate Chainlink oracle freshness. Miners could manipulate this timestamp.

## Impact
Attacker can make stale oracle prices seem valid, resulting in incorrect pricing.

## Code Snippet

 
``` solidity

require(block.timestamp - updatedAt <= heartbeatInterval, "ORACLE_HEARTBEAT_FAILED");

```
## Tool used

Manual Review

## Recommendation

Only impacts pricing, not critical contract assets. Other price validations also in place. Difficult for miner to consistently manipulate timestamp.

Use block.number instead of timestamp to validate freshness.

The vulnerability allows some manipulation of price calculations. But other factors limit the impact, so it is be a lower severity issue.

**Comment by nevillehuang** [comment]
Invalid, external admins are trusted.
