### ISSUE TITLE
bareli - borrowFeeRate is never  initialized

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#50]
bareli

high

# borrowFeeRate is never  initialized

## Summary
borrowFeeRate is neverinitialized and it has been used in accrueRate() and getTRate()..
## Vulnerability Detail
  function accrueRate() public {
        uint256 currentTimestamp = block.timestamp;
        if (currentTimestamp == lastUpdateTimestamp) {
            return;
        }
        uint256 timeDifference = block.timestamp - uint256(lastUpdateTimestamp);
   @>     tRate = tRate.decimalMul((timeDifference * _borrowFeeRate_) / Types.SECONDS_PER_YEAR + 1e18);
        lastUpdateTimestamp = currentTimestamp;
    }

    function getTRate() public view returns (uint256) {
        uint256 timeDifference = block.timestamp - uint256(lastUpdateTimestamp);
  @>      return tRate + (borrowFeeRate * timeDifference) / Types.SECONDS_PER_YEAR;
    }
}
## Impact
output will always be zero.
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JUSDBankStorage.sol#L53
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, correctly assigned [here](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/ed4a8483da11bcc04ced10de899038bcead087b3/smart-contract-EVM/src/JUSDBank.sol#L38)
