### ISSUE TITLE
detectiveking - Fee skirting in FundingRateArbitrage

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#55]
detectiveking

medium

# Fee skirting in FundingRateArbitrage

## Summary

Deposit fees can potentially be avoided in FundingRateArbitrage, especially for the first depositor

## Vulnerability Detail

Let's say you are the first depositor into the FundingRateArbitrage contract and you want to deposit `X` tokens. Instead of depositing `X`, just deposit an extremely small amount at first (say 1 token) and pay little to no fees. As the first depositor, you now have all the `earnUSDC` (representing shares of the total value), so just manually send a bunch of `USDC` into the contract now. You won't lose out when you withdraw, as the USDC you sent in will be part of the `getNetValue()` calculation. This just avoids the deposit fee. 

## Impact
Deposit fee skirting

## Code Snippet

https://github.com/JOJOexchange/smart-contract-EVM/blob/main/src/FundingRateArbitrage.sol#L258-L275

## Tool used

Manual Review

## Recommendation
Don't allow USDC buffer to be included in net value

**Comment by nevillehuang** [comment]
Invalid, known issue. Additionally, the example given is incorrect, 1 USDC is 1e6, so it is not possible to rounddown given appropriate `depositFeeRate` in 18 decimals (e.g, 0.1% is 1e15)

> 18. Asset losses of less than 1e-2 due to loss of precision are not considered.
