### ISSUE TITLE
bitsurfer - No way to take out USDC from JUSDBank

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#59]
bitsurfer

medium

# No way to take out USDC from JUSDBank

## Summary

There is no mechanism to pull out USDC from JUSDBank when FlashLoanLiquidate send USDC to JUSDBank.

## Vulnerability Detail

In `FlashLoanLiquidate` there is an updated code which will transfer USDC to JUSDBank when the liquidated remain USDC is not 0, as seen below:

```js
File: FlashLoanLiquidate.sol
73:         if (liquidateData.liquidatedRemainUSDC != 0) {
74:             IERC20(USDC).safeTransfer(address(jusdBank), liquidateData.liquidatedRemainUSDC);
75:         }
```

This means, JUSDBank will receive USDC, which can be used for any purpose related to JUSDBank operation.

But, in JUSDBank contract, there is no way to use or transfer this USDC to somewhere else, resulting the USDC will be locked inside the contract.

This issue quite similar with https://github.com/sherlock-audit/2023-04-jojo-judging/issues/347 but in this case, USDC. This is overlooked by dev, due to the updated code of FlashLoanLiquidate sending USDC to JUSDBank.

## Impact

USDC will be locked inside JUSDBank, unable to transfer to other address

## Code Snippet

https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/FlashLoanLiquidate.sol#L72-L75

## Tool used

Manual Review

## Recommendation

Consider to implement a way to retrieve USDC (or any token) from JUSDBank such as 'recover' token function, or else, create a specific function to moving out the USDC to somewhere else for any purpose

**Comment by nevillehuang** [comment]
Invalid, remaining liquidated amount stored in contract during a flashloan liquidate is transferred [here](https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JUSDBank.sol#L199)
