### ISSUE TITLE
T1MOH - JOJOOracleAdaptorWstETH.sol misses function `getMarkPrice()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#6]
T1MOH

medium

# JOJOOracleAdaptorWstETH.sol misses function `getMarkPrice()`

## Summary
JOJOOracleAdaptorWstETH.sol doesn't fully implement IPriceSource.sol. It misses function `getMarkPrice()`

## Vulnerability Detail
Code blocks which call function `getMarkPrice()` on Oracle contract will revert. The most significant is following:

Trader can't open trade in WstEth perp.
Here is function order:
```solidity
Perpetual.trade()
    JOJOView.isAllSafe()
        Liquidation._isAllMMSafe()
            Liquidation._isMMSafe()
                Liquidation.getTotalExposure()
                    IPriceSource.getMarkPrice()
```
Here you can see that function getMarkPrice() is called on perpetual oracle. For WstEth perpetual, oracle JOJOOracleAdaptorWstETH.sol is supposed to be used
```solidity
    function getTotalExposure(
        Types.State storage state,
        address trader
    )
        public
        view
        returns (int256 netValue, uint256 exposure, uint256 initialMargin, uint256 maintenanceMargin)
    {
        int256 netPositionValue;
        // sum net value and exposure among all markets
        for (uint256 i = 0; i < state.openPositions[trader].length;) {
            (int256 paperAmount, int256 creditAmount) = IPerpetual(state.openPositions[trader][i]).balanceOf(trader);
            Types.RiskParams storage params = state.perpRiskParams[state.openPositions[trader][i]];
@>          int256 price = SafeCast.toInt256(IPriceSource(params.markPriceSource).getMarkPrice());

            netPositionValue += paperAmount.decimalMul(price) + creditAmount;
            uint256 exposureIncrement = paperAmount.decimalMul(price).abs();
            exposure += exposureIncrement;
            maintenanceMargin += (exposureIncrement * params.liquidationThreshold) / Types.ONE;
            initialMargin += (exposureIncrement * params.initialMarginRatio) / Types.ONE;
            unchecked {
                ++i;
            }
        }
        netValue = netPositionValue + state.primaryCredit[trader] + SafeCast.toInt256(state.secondaryCredit[trader]);
    }
```

Also different functions like `FundingRateUpdateLimiter.getMaxChange()`, `Liquidation.requestLiquidation()` revert too because try to call `getMarkPrice()` on oracle

Note there is no function `getMarkPrice()`:
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/ed4a8483da11bcc04ced10de899038bcead087b3/smart-contract-EVM/src/oracle/OracleAdaptorWstETH.sol#L13

## Impact
WstEth Perpetual can't be used.

## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/ed4a8483da11bcc04ced10de899038bcead087b3/smart-contract-EVM/src/oracle/OracleAdaptorWstETH.sol#L13

## Tool used

Manual Review

## Recommendation
Add missing function

**Comment by nevillehuang** [comment]
Invalid, intended that `JOJOOracleAdaptorWstETH` does not support mark price
