### ISSUE TITLE
bareli - Gas Limit

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#60]
bareli

medium

# Gas Limit

## Summary
Gas Limit: There is no check on the number of calls being made in a single multiCall invocation. If too many calls are included, the transaction could run out of gas, causing it to fail.

## Vulnerability Detail
 for (uint256 i; i < callData.length; i++) {
            (bool success, bytes memory res) = address(this).delegatecall(callData[i]);
            if (success == false) {
                assembly {
                    let ptr := mload(0x40)
                    let size := returndatasize()
                    returndatacopy(ptr, 0, size)
                    revert(ptr, size)
                }
            }
            returnData[i] = res;
        }
    }

## Impact
 If too many calls are included, the transaction could run out of gas, causing it to fail.

## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JUSDMulticall.sol#L15
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid based on sherlock's OOG [rules](https://docs.sherlock.xyz/audits/judging/judging#viii.-list-of-issue-categories-that-are-considered-valid)

> 4. Out of Gas: Issues that result in Out of Gas errors either by the malicious user filling up the arrays or there is a practical call flow that results in OOG can be considered a valid medium or in cases of blocking all user funds forever maybe a valid high.
Exception: In case the array length is controlled by the trusted admin/owner or the issue describes an impractical usage of parameters to reach OOG state then these submissions would be considered as low.
