### ISSUE TITLE
bareli - validate the from address.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#62]
bareli

medium

# validate the from address.

## Summary
The repayToBank function does not validate the from parameter, which is not used in the function body. This could be a mistake or an oversight.

## Vulnerability Detail
 function repayToBank(address from, address to) external onlyAdminWhiteList {
        uint256 USDCBalance = IERC20(USDC).balanceOf(address(this));
        if (USDCBalance > 0) {
            IERC20(USDC).approve(JUSDExchange, USDCBalance);
            IJUSDExchange(JUSDExchange).buyJUSD(USDCBalance, address(this));
        }
        uint256 balance = IERC20(JUSD).balanceOf(address(this));
        IJUSDBank(JusdBank).repay(balance, to);
        emit HelpToTransfer(from, to, balance);
    }
## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/JUSDRepayHelper.sol#L50
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, since `from` is not used, it is not required to be validated
