### ISSUE TITLE
giraffe - Missing fallback oracle in OracleAdaptorWstETH

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#68]
giraffe

medium

# Missing fallback oracle in OracleAdaptorWstETH

## Summary
Unlike the other oracle adaptors, OracleAdaptorWstETH.sol appears to be missing a fallback oracle to which price obtained should be compared against.
## Vulnerability Detail
From [JOJO Docs](https://about.jojo.exchange/jojo-1/trade/pricing#jojo-oracle-architecture), their oracle architecture was designed to use Chainlink as the primary oracle provider and with Uniswap V3 or JOJO self oracle as a fallback.

The two other oracle adaptors, OracleAdaptor.sol and UniswapPriceAdaptor.sol have a fallback oracle implemented, where price from Chainlink is compared against price from the fallback oracle. If the deviation exceeds a threshold, then price is rejected. 

```solidity
require((diff * 1e18) / chainLinkPrice <= priceThreshold, "deviation is too big");
```

For OracleAdaptorWstETH.sol however, there is no fallback oracle implemented and price is not checked against another source. This goes against JOJO's architecture as described in their docs, and checking price against reasonable limits is also advised by [Chainlink](https://docs.chain.link/data-feeds#check-the-latest-answer-against-reasonable-limits).
## Impact
In the event that Chainlink returns faulty price, it will be consumed by JOJO's contracts which could lead to negative outcomes such as unfair liquidations or attackers taking advantage of the inaccurate price.

## Code Snippet
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/oracle/OracleAdaptorWstETH.sol#L40
https://github.com/sherlock-audit/2023-12-jojo-exchange-update/blob/main/smart-contract-EVM/src/oracle/OracleAdaptor.sol#L63
## Tool used
Manual Review

## Recommendation
Similar to the other oracle adaptors, implement a fallback oracle using Uniswap V3 or self-oracle and do a deviation check before returning the price feed.

**Comment by nevillehuang** [comment]
Invalid, this is a design suggestion, and known issue.

> 7. Reliability of Price

**Comment by giraffe0x** [comment]
Escalate. 

I don't agree this is a design suggestion as it clearly deviates from the protocol [docs](https://about.jojo.exchange/jojo-1/trade/pricing#jojo-oracle-architecture) and stands out from the other oracle adaptors which **do** have a fallback oracle.

Could we get the sponsor @JoscelynFarr  to comment if this will be fixed? Or why such a design was selected for the WstETH oracle specifically? 

If this will be fixed, then I think it adds value to the protocol and should be considered valid. Thank you.

**Comment by sherlock-admin** [comment]
> Escalate. 
> 
> I don't agree this is a design suggestion as it clearly deviates from the protocol [docs](https://about.jojo.exchange/jojo-1/trade/pricing#jojo-oracle-architecture) and stands out from the other oracle adaptors which **do** have a fallback oracle.
> 
> Could we get the sponsor @JoscelynFarr  to comment if this will be fixed? Or why such a design was selected for the WstETH oracle specifically? 
> 
> If this will be fixed, then I think it adds value to the protocol and should be considered valid. Thank you. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
I think this is an info/low issue for this case

**Comment by nevillehuang** [comment]
@giraffe0x I believe this issue is invalid/informational, it was already explicitly mentioned that chainlink oracle failure/reliability is out of scope, so it is up to the protocol whether or not they require a fallback oracle for this particular design of the wstETH oracle. Additionally, the price threshold is determined by the admin, they can and will set a reasonable small enough number, so if the deviation is too big, it infact will be reverted accordingly.

> 7. Reliability of Price
> 8. Third Party Dependencies: chainlink Oracle Failed

**Comment by Czar102** [comment]
Agree with the Lead Judge, planning to leave the issue as is and reject the escalation.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [giraffe0x](https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/68/#issuecomment-1913137446): rejected
