### ISSUE TITLE
millietez - Unprotected call to a custom contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-jojo-exchange-update-judging#90]
millietez

high

# Unprotected call to a custom contract

## Summary
Unprotected call to a custom contract. 

## Vulnerability Detail
The `DepositStableCoinToDealer` contract provides the functionality for depositing stable coins into the JOJO Exchange dealer and makes a call to a custom contract in line 54 https://github.com/JOJOexchange/smart-contract-EVM/blob/aca8529979caa9e99ea48948645e041925731ef4/src/DepositStableCoinToDealer.sol#L54 

Users can specify contracts for authorization and exchange while adhering to a whitelist. The inclusion of contracts in the whitelist is done through mapping; however, this does not guarantee that the added contracts will not have a negative impact on the protocol.

If a malicious actor successfully passes the whitelist check and transmits data to the contract address, if by mistake token address is added to the whitelist - the attacker will be able to call transferFrom function on the token contract, and withdraw all pending allowance from users wallets to the attackers address. This occurs due to the absence of additional checks on the function selector, creating a vulnerability in the system.

Attack example: 
https://blog.solidityscan.com/rubic-exchange-hack-analysis-whitelisting-does-not-always-work-effectively-d3aeb0816af4

## Impact
User funds theft

## Code Snippet
https://github.com/JOJOexchange/smart-contract-EVM/blob/aca8529979caa9e99ea48948645e041925731ef4/src/DepositStableCoinToDealer.sol#L54

## Tool used
Manual Review

## Recommendation
Adding a mechanism to verify function signatures, creating a blacklist for function selector signatures, and implementing additional checks when interacting with external contracts.

**Comment by nevillehuang** [comment]
Invalid, this consitutes admin input error not valid based on sherlock [rules see point 5](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)
